# Site settings
name: BukuKelas.Com
title: Portal Informasi Pendidikan
email: "wahyu243@gmail.com"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bukukelas.com" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/images/header-brand.png
description: "BukuKelas.com menyajikan berbagai informasi informatif tentang pendidikan, dokumen, rpp, buku, tutorial, berita, dll."
keywords: "buku kelas, buku pendidikan, buku sd, buku smp, buku sma/smk, buku pendidikan khusus, buku abk"
mailclimp: "https://bukukelas.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=4784863884"
facebook: https://facebook.com/bukukelas
instagram: https://instagram.com/bukukelas
twitter: https://twitter.com/bukukelas
pinterest: https://pinterest.com/bukukelas

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-timeago
  - jekyll-last-modified-at
  - jekyll-sitemap

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'

# Site configuration for the Jekyll 2 Pagination Gem
pagination:
  enabled: true
  debug: true
  collection: "posts"
  per_page: 8
  permalink: "/pages/:num/" # Pages are simple html files
  title: ":title - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  category: "posts"
  tag: ""
  locale: ""
  trail:
    before: 2
    after:
  extension: "html"
  indexpage: "index"

autopages:
  enabled: true
  categories:
    layouts:
      - "category.html"
    title: ":cat"
    permalink: "/category/:cat"
  collections:
    layouts:
      - "category.html"
    title: " :coll" # :coll is replaced by the collection name
    permalink: "/:coll/"

  tags:
    layouts:
      - "tag.html"
    title: ":tag" # :tag is replaced by the tag name
    permalink: "/tag/:tag"

tag_page_layout: category
tag_page_dir: tag
tag_permalink_style: pretty

defaults:
- scope:
    path: _pages
    type: pages
  values:
    layout: page
    author_name: wahyu243
    author_id: 1
    toc: true
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    author_name: wahyu243
    author_id: 1
    toc: true
    
collections:
  pages:
    permalink: "/:path"
    output: true
    pagination:
       enabled: true    
    toc: true
    
  posts:
    permalink: "/:categories/:title"
    output: true
    pagination:
       enabled: true
    toc: true
  authors:
    output: true
    permalink: /author/:path/

feed:
  collections:
    posts:
      path: "/index.xml"

toc:
  min_level: 1
  max_level: 10
  ordered_list: false
  no_toc_section_class: 'toc-l'
  list_class: t-o-c
  sublist_class: 'toc-p'
  item_class: 'toc-p'
  item_prefix: 'toc-p'
  
  compress_html:
  clippings: all
  comments: [""]
  endings: [all]
  profile: false
  blanklines: false
  ignore:
    envs: []

# Google, Bing
gtag-manager: G-DCLZVD57WN
google_verification: KVq75QFLhLp8UoW-Mf-ifdxcDsciWvOnDrQEn25KS5M
bing_verification: 45256F6C01A5B0893737B4B675E797AE
