####################################################
#
# Welcome to NewsFeed Jekyll Template
#
# Product Link : https://themeix.com/product/NewsFeed-jekyll-template/
# Version : v1.0.0
#
####################################################

# Site settings
title: "Newsfeed - Jekyll Premim Theme"
email: "themeix@gmail.com"
baseurl: "/jekyllTest-newsfeed" # the subpath of your site, e.g. /blog
url: "https://akashmdiu.github.io/jekyllTest-newsfeed" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/images/header-brand.png
description: "NewsFeed is a responsive Jekyll template for your business website"
keywords: "jekyll, minimal jekyll, jekyll theme, responsive jekyll, seo friendly blog, super fast blog, responsive"
mailclimp: "https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=4784863884"
facebook: https://facebook.com/themeix
instagram: https://instagram.com/themeix
twitter: https://twitter.com/themeix_com
pinterest: https://pinterest.com/themeix

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-timeago


# Site configuration for the Jekyll 2 Pagination Gem
pagination:
  enabled: true
  debug: true
  collection: "posts"
  per_page: 8
  permalink: "/pages/:num/" # Pages are simple html files
  title: ":title - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  category: "posts"
  tag: ""
  locale: ""
  trail:
    before: 2
    after:
  extension: "html"
  indexpage: "index"

autopages:
  enabled: true
  categories:
    layouts:
      - "category.html"
    title: ":cat"
    permalink: "/category/:cat"
  collections:
    layouts:
      - "category.html"
    title: " :coll" # :coll is replaced by the collection name
    permalink: "/:coll/"

  tags:
    layouts:
      - "tag.html"
    title: ":tag" # :tag is replaced by the tag name
    permalink: "/tag/:tag"

tag_page_layout: category
tag_page_dir: tag
tag_permalink_style: pretty

    
collections:
  authors:
    output: true
    permalink: /author/:path/

feed:
  collections:
    posts:
      path: "/index.xml"
